language: android
notifications:
  email: false
sudo: false

android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - sys-img-x86-android-24

script:
  - "./gradlew assembleRelease"

before_deploy:
  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/app-release.apk
deploy:
  provider: releases
  api_key:
    secure: 322704836d634833447367cd61a92fedbac97461
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true